name: Pipeline

on:
  push:
    branches: [ main, exercise ]
  pull_request:
    branches: [ main, exercise ]
  workflow_dispatch:

env:
  BUILD_TYPE: Coverage

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} 

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        pip install -r ${{github.workspace}}/test/requirements.txt
        cmake --build . -t check

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
